# Software Name : HSLinUCB
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: GPL-2.0
#
# This software is distributed under the GNU General Public License v2.0 license
#
# Author: David DELANDE <david.delande@orange.com> et al.

- name: install nginx
  apt: package=nginx update_cache=yes
  notify: nginx restart
  environment:
    - http_proxy: "http://{{hostvars[groups['master'][0]].ansible_default_ipv4.address}}:3128"
    - https_proxy: "http://{{hostvars[groups['master'][0]].ansible_default_ipv4.address}}:3128"

- name: Remove default virtual host
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
  notify: nginx restart

- name: Retrieve prometheus component informations
  shell: "kubectl get svc -n istio-system prometheus -o json"
  register: prometheus_component_tmp
  delegate_to: "{{ groups['master'][0] }}"

- set_fact:
    prometheus_component: "{{ prometheus_component_tmp.stdout|from_json }}"

- name: Retrieve grafana component informations
  shell: "kubectl get svc -n istio-system prometheus-grafana -o json"
  register: grafana_component_tmp
  delegate_to: "{{ groups['master'][0] }}"

- set_fact:
    grafana_component: "{{ grafana_component_tmp.stdout|from_json }}"

- name: Deploy nginx configuration file
  template:
    src: "reverse_proxy.conf.j2"
    dest: "/etc/nginx/sites-available/reverse_proxy.conf"
  notify: nginx restart

- name: Activate nginx configuration file
  file:
    src: "/etc/nginx/sites-available/reverse_proxy.conf"
    dest: "/etc/nginx/sites-enabled/reverse_proxy.conf"
    state: link
  notify: nginx restart

- name: Remove default index page
  file:
    path: "/var/www/html/index.nginx-debian.html"
    state: absent

- name: Deploy index page
  template:
    src: "index.html.j2"
    dest: "/var/www/html/index.html"
