# Software Name : HSLinUCB
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: GPL-2.0
#
# This software is distributed under the GNU General Public License v2.0 license
#
# Author: David DELANDE <david.delande@orange.com> et al

- name: Create ansible inventory
  hosts: localhost
  tasks:
    - openstack.cloud.server_info:
        validate_certs: False
        auth: "{{ cloud_auth }}"
