all:
  vars:
     openstack_network: 192.168.0.0/24
master:
  hosts:
    master1:
      ansible_host: 192.168.0.60 
      ansible_user: cloud
worker:
  hosts:
    worker1:
      ansible_host: 192.168.0.57
      ansible_user: cloud
    worker2:
      ansible_host: 192.168.0.113
      ansible_user: cloud
    worker3:
      ansible_host: 192.168.0.66
      ansible_user: cloud
stress:
  hosts:
    stress1:
      ansible_host: 192.168.0.44
      ansible_user: cloud
    stress2:
      ansible_host: 192.168.0.161
      ansible_user: cloud
agent:
  hosts:
    agent1:
      ansible_host: 192.168.0.54
      ansible_user: cloud
  vars:
     jupyterlab_account:
        - user:
            login: david
            password: davidpassword
