#!/usr/bin/python3

# Software Name : HSLinUCB
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: GPL-2.0
#
# This software is distributed under the GNU General Public License v2.0 license
#
# Author: David DELANDE <david.delande@orange.com> et al.

from random import uniform
import time
import os
import math
import requests
from cgi import parse_qs

print('Content-type: text/plain') # the mime-type header.
print() # header must be separated from body by 1 empty line.
ComponentName = "front" if (os.environ.get("COMPONENT_NAME") == None) else os.environ.get("COMPONENT_NAME")

start = time.time()
argument = parse_qs(os.environ['QUERY_STRING'])
time.sleep(float(argument.get('time',[0])[0])/1000)
stop = time.time()
print("Done in:" + str(stop - start) + " by " + ComponentName)
