# Software Name : HSLinUCB
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: GPL-2.0
#
# This software is distributed under the GNU General Public License v2.0 license
#
# Author: David DELANDE <david.delande@orange.com> et al

- name: Create hslinucb security group
  openstack.cloud.security_group:
    state: present
    name: sg-hslinucb
    auth: "{{ cloud_auth }}"
    validate_certs: False
    description: "Allow full internal communication between hslinucb VM"

- name: Allow traffic from hslinucb to hslinucb
  openstack.cloud.security_group_rule:
    state: present
    security_group: "sg-hslinucb"
    remote_group: "sg-hslinucb"
    auth: "{{ cloud_auth }}"
    validate_certs: False

- name: Allow ssh traffic from external IP
  openstack.cloud.security_group_rule:
    state: present
    security_group: "sg-hslinucb"
    remote_ip_prefix: "{{ item }}"
    protocol: "tcp"
    direction: "ingress"
    port_range_min: "22"
    port_range_max: "22"
    auth: "{{ cloud_auth }}"
    validate_certs: False
  when: external_authorized_ip is defined and external_authorized_ip != ""
  with_items: "{{ external_authorized_ip }}"

- name: Allow web traffic from external IP
  openstack.cloud.security_group_rule:
    state: present
    security_group: "sg-hslinucb"
    remote_ip_prefix: "{{ item }}"
    protocol: "tcp"
    direction: "ingress"
    port_range_min: "80"
    port_range_max: "80"
    auth: "{{ cloud_auth }}"
    validate_certs: False
  when: external_authorized_ip is defined and external_authorized_ip != ""
  with_items: "{{ external_authorized_ip }}"
