# Software Name : HSLinUCB
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: GPL-2.0
#
# This software is distributed under the GNU General Public License v2.0 license
#
# Author: David DELANDE <david.delande@orange.com> et al.

- name: generate metric-server deployment file
  template:
    src: metric-server-deploy.yaml
    dest: /tmp/metric-server-deploy.yaml

- name: Deploy metric server in kubernetes
  shell: "kubectl apply -f /tmp/metric-server-deploy.yaml"
  register: task_result
  until: task_result.rc == 0
  retries: 10
  delay: 5
  when: groups['master'][0] == inventory_hostname
